apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama5gpu
  namespace: ollama
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: ollama
  template:
    metadata:
      labels:
        name: ollama
    spec:
      containers:
      - name: ollama
        image: ollama/ollama:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 11434
          protocol: TCP
        resources:
          limits:
            nvidia.com/gpu: 5
        volumeMounts:
        - name: models
          mountPath: /root/.ollama
        env:
        - name: OLLAMA_DEBUG
          value: "1"
        - name: OLLAMA_SCHED_SPREAD
          value: "1"
        # If the model will entirely fit on any single GPU, 
        # Ollama will load the model on that GPU by default. 
        # This typically provides the best performance 
        # as it reduces the amount of data transferring across the PCI bus during inference.
        # OLLAMA_SCHED_SPREAD=1 will spread the model across all GPUs by force.
        - name: OLLAMA_KEEP_ALIVE
          value: "-1"
      volumes:
      - name: models
        hostPath:
          path: /home/test/.ollama
          type: DirectoryOrCreate
      runtimeClassName: nvidia
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
---