apiVersion: v1
kind: Pod
metadata:
  name: harbor-cli
  namespace: harbor
spec:
  nodeSelector:
    nickname: dell1
  containers:
  - name: docker-client
    image: docker:20.10.23-dind
    command:
    - sh
    - -c
    - sleep infinity
    securityContext:
      runAsUser: 0
    volumeMounts:
    - name: docker-sock
      mountPath: /var/run/docker.sock
    - name: config
      mountPath: /etc/docker/daemon.json
  volumes:
  - name: docker-sock
    hostPath:
      path: /var/run/docker.sock
  - name: config
    hostPath:
      path: /etc/docker/daemon.json
  restartPolicy: Never