apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-harbor-trivy
  namespace: harbor
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: local-harbor-trivy
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-harbor-redis
  namespace: harbor
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: local-harbor-redis
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-harbor-db
  namespace: harbor
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: local-harbor-db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-harbor-jobservice
  namespace: harbor
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: local-harbor-jobservice
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-harbor-registry
  namespace: harbor
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: local-harbor-registry
